Repository geezers-io/Stock2U-api, pull requests merged in 2023-11, with the labels that each got.

#49 Feature/su 131
  build.gradle
  src/main/java/com/hack/stock2u/chat/api/ConnectionTestApi.java
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/api/StompMessageController.java
  src/main/java/com/hack/stock2u/chat/config/StompWepSocketConfig.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChangeStatusRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReportRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationApproveRequest.java
  src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/chat/web/StompWepSocketConfig.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/resources/application.yaml
  src/main/resources/templates/chat.html
Labels: feat, fix

#51 feature: 웹 소켓 인증 및 인가 로직 작성
  build.gradle
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/authentication/service/SessionManager.java
  src/main/java/com/hack/stock2u/chat/api/StompMessageApi.java
  src/main/java/com/hack/stock2u/chat/config/CredentialsInterceptor.java
  src/main/java/com/hack/stock2u/chat/config/ErrorHandler.java
  src/main/java/com/hack/stock2u/chat/config/StompWepSocketConfig.java
  src/main/java/com/hack/stock2u/chat/web/StompWepSocketConfig.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/global/filter/HttpLogger.java
  src/main/resources/application.yaml
  src/main/resources/templates/chat.html
Labels: feat

#52 feat: 예약(채팅) - [BE] 각 사용자에 대한 알람 채널 생성 및 구독 API
  src/main/java/com/hack/stock2u/chat/config/CredentialsInterceptor.java
  src/main/java/com/hack/stock2u/chat/service/ReservationMessageHandler.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/constant/MessageTemplate.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
Labels: feat

#53 fix: 채팅방목록 400에러
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
Labels: fix

#56 Feature: 카운팅+룸id 메세지로 전달, 기존 메세지에서 보내야할 정보 objectmapper로 직렬화
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/config/ObjectMapperConfig.java
  src/main/java/com/hack/stock2u/chat/dto/ChatMessageObjectForSerialize.java
  src/main/java/com/hack/stock2u/chat/dto/ReservationApproveToMessage.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationApproveRequest.java
  src/main/java/com/hack/stock2u/chat/dto/response/AlertIdAndMessage.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/PurchaserSellerReservationsResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ReservationMessageResponse.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/utils/JsonSerializer.java
Labels: feat

#60 feat: 채팅 내역 불러오기 API 작성
  src/main/java/com/hack/stock2u/chat/api/ChatHttpApi.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatHistories.java
  src/main/java/com/hack/stock2u/chat/repository/MessageChatMongoRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatHistoryLoader.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/MongoChatListener.java
  src/main/java/com/hack/stock2u/global/service/SequenceGeneratorService.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
  src/main/java/com/hack/stock2u/models/embed/MongoAutoIncrementSequence.java
Labels: feat

#57 [경축 첫 PR] 구매 기록 API 작성
  src/main/java/com/hack/stock2u/models/Buyer.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/product/service/PurchasedHistoryService.java
  src/main/java/com/hack/stock2u/user/api/MyApi.java
  src/main/java/com/hack/stock2u/user/dto/PurchasedHistory.java
  src/main/java/com/hack/stock2u/user/dto/SearchDate.java
  src/main/java/com/hack/stock2u/user/repository/BuyerDslRepository.java
  src/main/java/com/hack/stock2u/user/repository/JpaBuyerRepository.java
Labels: feat

#61 feat: 예약정보로 재고 조회 API
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/repository/MessageChatMongoRepository.java
  src/main/java/com/hack/stock2u/chat/repository/ReservationProductDslRepository.java
  src/main/java/com/hack/stock2u/chat/service/ReservationProductService.java
  src/main/java/com/hack/stock2u/global/repository/ProductDslUtils.java
  src/main/java/com/hack/stock2u/product/dto/ProductSummary.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/user/dto/SellerDetailsLatLng.java
  src/main/java/com/hack/stock2u/user/repository/SellerDslRepository.java
Labels: feat, refactor

#62 feat: 채팅 서비스 리팩터링 및 프로필 이미지 로직 추가
  src/main/java/com/hack/stock2u/chat/dto/MessageCreation.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/file/service/ImageProvider.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
Labels: feat, refactor

#59 feat: 판매자 판매 관리 API
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/repository/ReservationDslRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatPageMessageHandler.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/product/exception/ProductException.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/product/repository/ProductDslRepository.java
  src/main/java/com/hack/stock2u/user/api/SellerApi.java
  src/main/java/com/hack/stock2u/user/dto/SellerManagementSummary.java
  src/main/java/com/hack/stock2u/user/dto/SellerProducts.java
  src/main/java/com/hack/stock2u/user/repository/JpaUserRepository.java
  src/main/java/com/hack/stock2u/user/repository/SellerDslRepository.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
Labels: feat, fix
