Repository geezers-io/Stock2U-api, pull requests merged in 2023-10, with the labels that each got.

#5 feat: Spring 빌드 및 실행을 위한 Docker 스크립트 작성
  .env.example
  Dockerfile
  docker-compose.yml
  settings.gradle
  src/main/java/com/hack/mapstockapi/controller/TestController.java
  src/main/resources/application.yaml
Labels: feat

#6 feature: openapi-docs 추가 및 도커 실행 테스트
  build.gradle
  src/main/java/com/hack/stock2u/Application.java
  src/main/java/com/hack/stock2u/controller/TestController.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/logback/SimpleLogTest.java
Labels: feat

#7 feature: RDB 엔티티 객체 모델 작성
  src/main/java/com/hack/stock2u/constant/ProductType.java
  src/main/java/com/hack/stock2u/constant/ReservationStatus.java
  src/main/java/com/hack/stock2u/constant/UserRole.java
  src/main/java/com/hack/stock2u/models/Attach.java
  src/main/java/com/hack/stock2u/models/Buyer.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/ProductImage.java
  src/main/java/com/hack/stock2u/models/Report.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/models/SellerDetails.java
  src/main/java/com/hack/stock2u/models/Subscription.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/models/embed/BasicDateColumn.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/authentication/constant/SimpleUserRoleTest.java
Labels: feat

#9 feat: 각 인증 벤더사를 의미하는 AuthVendor 객체와 컨버터 작성
  build.gradle
  src/main/java/com/hack/stock2u/authentication/service/AuthVendorEnumConverter.java
  src/main/java/com/hack/stock2u/constant/AuthVendor.java
  src/main/java/com/hack/stock2u/global/config/WebConfig.java
Labels: feat

#10 feat: Security 로직 작성을 위한 기반 코드 작성
  src/main/java/com/hack/stock2u/authentication/service/AppGrantedAuthority.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetails.java
  src/main/java/com/hack/stock2u/constant/AuthVendor.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/models/Buyer.java
  src/main/java/com/hack/stock2u/models/Report.java
  src/main/java/com/hack/stock2u/user/repository/JpaUserRepository.java
  src/main/resources/logback-test.xml
  src/test/java/com/hack/stock2u/constant/AuthVendorTest.java
  src/test/java/com/hack/stock2u/global/config/SecurityConfigTest.java
Labels: feat

#12 feat: 예외 처리 시스템 설계 및 작성
  config/checkstyle/checkstyle.xml
  src/main/java/com/hack/stock2u/constant/ProductType.java
  src/main/java/com/hack/stock2u/constant/ReservationStatus.java
  src/main/java/com/hack/stock2u/constant/UserRole.java
  src/main/java/com/hack/stock2u/global/exception/BasicErrorCase.java
  src/main/java/com/hack/stock2u/global/exception/BasicErrorResponse.java
  src/main/java/com/hack/stock2u/global/exception/BasicException.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/user/UserException.java
  src/main/java/com/hack/stock2u/user/repository/JpaUserRepository.java
  src/test/java/com/hack/stock2u/authentication/constant/SimpleUserRoleTest.java
Labels: feat

#11 feat: 카카오 OAuth 로그인 구현 (Session)
  build.gradle
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/config/KakaoProperties.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/dto/LoginResponse.java
  src/main/java/com/hack/stock2u/authentication/dto/TokenSet.java
  src/main/java/com/hack/stock2u/authentication/dto/UrlJson.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetailService.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetails.java
  src/main/java/com/hack/stock2u/authentication/service/client/AuthUserDetail.java
  src/main/java/com/hack/stock2u/authentication/service/client/KaKaoAccount.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoClient.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoTokenResponse.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoUserDetailsResponse.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/KakaoURLStrategy.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/LoginStrategyBranch.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/LoginURLCreateStrategy.java
  src/main/java/com/hack/stock2u/controller/TestController.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/global/config/SecurityConfigTest.java
Labels: config, feat

#13 feat: Twilio SMS 서비스와 Spring Application 연결
  build.gradle
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoTokenResponse.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoUserDetailsResponse.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/KakaoURLStrategy.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/LoginStrategyBranch.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/LoginUrlCreateStrategy.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
  src/main/java/com/hack/stock2u/global/factory/SmsFactory.java
  src/main/resources/application.yaml
  src/main/resources/externel.yaml
  src/test/java/com/hack/stock2u/global/factory/SmsFactoryTest.java
Labels: feat

#14 feat: 회원 가입 인증코드 발송 및 검증 API 작성
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/AuthCodeProvider.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/SmsMessage.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/global/factory/SmsFactory.java
  src/main/java/com/hack/stock2u/utils/Convertor.java
  src/main/java/com/hack/stock2u/utils/OneTimeCodeGenerator.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/utils/ConvertorTest.java
  src/test/java/com/hack/stock2u/utils/OneTimeCodeGeneratorTest.java
Labels: feat

#15 feat: 도로명 주소 조회 API
  config/checkstyle/checkstyle.xml
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroAddress.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroAddressItem.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroCommon.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroPageDetails.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroResponse.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroResult.java
  src/main/java/com/hack/stock2u/authentication/dto/doro/DoroSearchResponse.java
  src/main/java/com/hack/stock2u/authentication/service/RoadNameAddressService.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/resources/application.yaml
  src/main/resources/externel.yaml
Labels: feat

#17 feat: 일반 사용자 - 회원가입 및 로그인 API (Only KAKAO)
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/dto/LoginResponse.java
  src/main/java/com/hack/stock2u/authentication/dto/UserDetails.java
  src/main/java/com/hack/stock2u/authentication/service/AuthCodeProvider.java
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetailService.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetails.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/models/embed/BasicDateColumn.java
  src/main/java/com/hack/stock2u/user/repository/JpaUserRepository.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/global/config/SecurityConfigTest.java
Labels: feat

#18 feat: 로그아웃 & 회원 탈퇴 API 구현
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/service/AppGrantedAuthority.java
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetails.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/resources/application.yaml
Labels: feat

#20 feat: 은행 리스트 조회 API
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/Bank.java
  src/main/java/com/hack/stock2u/authentication/service/BankInfoGenerator.java
  src/main/java/com/hack/stock2u/constant/BankCode.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
Labels: feat

#21 feat: 인증 API 보안 절차 강화 및 네이밍 변경
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/dto/LoginResponse.java
  src/main/java/com/hack/stock2u/authentication/dto/SignInResponse.java
  src/main/java/com/hack/stock2u/authentication/service/AuthAccessDeniedHandler.java
  src/main/java/com/hack/stock2u/authentication/service/AuthCodeProvider.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/KakaoURLStrategy.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/SignInStrategyBranch.java
  src/main/java/com/hack/stock2u/authentication/service/strategy/SignInUrlCreateStrategy.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/global/config/SecurityConfigTest.java
Labels: feat

#22 feat: 스프링 애플리케이션 요청 DTO validation 로직 작성
  build.gradle
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/dto/SignInResponse.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/SignupValidator.java
  src/main/java/com/hack/stock2u/constant/UserRole.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/SellerDetails.java
  src/main/java/com/hack/stock2u/models/User.java
  src/test/java/com/hack/stock2u/authentication/constant/SimpleUserRoleTest.java
Labels: feat

#23 feature: OpenAPI Docs 내용 추가 및 개선
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/client/KakaoClient.java
  src/main/java/com/hack/stock2u/global/config/SwaggerConfig.java
Labels: feat

#24 feat: 채팅 구현중 (WIP)
  src/main/java/com/hack/stock2u/chat/config/StompWebSocketConfig.java
  src/main/java/com/hack/stock2u/chat/controller/MessageController.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChatRequest.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatResponses.java
  src/main/java/com/hack/stock2u/chat/service/ChatService.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/user/repository/JpaChatRoomRepository.java
  src/main/java/com/hack/stock2u/user/repository/MessageChatMongoRepository.java
Labels: feat

#26 feat: S3 객체 연결, 파일 업로드 / 삭제 API
  build.gradle
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/SessionManager.java
  src/main/java/com/hack/stock2u/file/api/FileUploadApi.java
  src/main/java/com/hack/stock2u/file/config/S3Config.java
  src/main/java/com/hack/stock2u/file/dto/FileIdListResponse.java
  src/main/java/com/hack/stock2u/file/dto/FilesUploadRequest.java
  src/main/java/com/hack/stock2u/file/dto/SimpleFile.java
  src/main/java/com/hack/stock2u/file/exception/FileException.java
  src/main/java/com/hack/stock2u/file/repository/AttachRepository.java
  src/main/java/com/hack/stock2u/file/service/FileNameProvider.java
  src/main/java/com/hack/stock2u/file/service/FileUploadService.java
  src/main/java/com/hack/stock2u/file/service/S3Service.java
  src/main/java/com/hack/stock2u/global/exception/GlobalException.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/models/Attach.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/resources/application.yaml
  src/test/java/com/hack/stock2u/file/service/S3ServiceTest.java
  src/test/java/com/hack/stock2u/learn/AntPatternMatchTest.java
Labels: feat

#27 feat: 파일 리사이즈 로직 작성 / 레디스 세션 연동 / 사용자 관련 API / 스웨거 개선
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/SessionManager.java
  src/main/java/com/hack/stock2u/authentication/service/UserDetails.java
  src/main/java/com/hack/stock2u/file/api/FileUploadApi.java
  src/main/java/com/hack/stock2u/file/service/FileUploadService.java
  src/main/java/com/hack/stock2u/file/service/S3Service.java
  src/main/java/com/hack/stock2u/models/SellerDetails.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/models/embed/BasicDateColumn.java
  src/main/java/com/hack/stock2u/user/api/MyApi.java
  src/main/java/com/hack/stock2u/user/api/PurchaserApi.java
  src/main/java/com/hack/stock2u/user/api/SellerApi.java
  src/main/java/com/hack/stock2u/user/dto/PurchaserRequest.java
  src/main/java/com/hack/stock2u/user/dto/SellerResponse.java
  src/main/java/com/hack/stock2u/user/service/MyService.java
  src/main/java/com/hack/stock2u/user/service/PurchaserService.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
Labels: feat

#28 Feature/su 68
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/chat/config/StompWebSocketConfig.java
  src/main/java/com/hack/stock2u/chat/controller/ChatRoomController.java
  src/main/java/com/hack/stock2u/chat/controller/MessageController.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChatRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChatRoomRequestDto.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationRoomsRequest.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatMessageResponses.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatRoomResponse.java
  src/main/java/com/hack/stock2u/chat/repository/JpaChatRoomRepository.java
  src/main/java/com/hack/stock2u/chat/repository/MessageChatMongoRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/ChatRoomService.java
  src/main/java/com/hack/stock2u/chat/service/ChatService.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/models/embed/BasicDateColumn.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/user/repository/JpaChatRoomRepository.java
  src/main/java/com/hack/stock2u/user/repository/MessageChatMongoRepository.java
Labels: feat

#29 fix: 레디스 세션 정상동작하도록 수정
  src/main/java/com/hack/stock2u/authentication/dto/SessionUser.java
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/authentication/service/SessionManager.java
  src/main/java/com/hack/stock2u/file/repository/JpaAttachRepository.java
  src/main/java/com/hack/stock2u/file/service/FileUploadService.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
  src/main/java/com/hack/stock2u/user/service/MyService.java
  src/main/java/com/hack/stock2u/user/service/PurchaserService.java
Labels: fix

#30 feat: 잔여 재고 판매 게시글 등록 API
  src/main/java/com/hack/stock2u/file/dto/SimpleFile.java
  src/main/java/com/hack/stock2u/models/Buyer.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/ProductImage.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/product/api/ProductApi.java
  src/main/java/com/hack/stock2u/product/dto/ProductDetails.java
  src/main/java/com/hack/stock2u/product/dto/ProductRequest.java
  src/main/java/com/hack/stock2u/product/dto/SellerDetails.java
  src/main/java/com/hack/stock2u/product/exception/ProductException.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductImageRepository.java
  src/main/java/com/hack/stock2u/product/service/ProductService.java
  src/main/java/com/hack/stock2u/user/repository/JpaBuyerRepository.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
  src/main/resources/application.yaml
Labels: feat

#31 feat: HTTP 커스텀 로깅 / API 별 권한 체크 기능
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/service/AuthManager.java
  src/main/java/com/hack/stock2u/global/config/WebConfig.java
  src/main/java/com/hack/stock2u/global/filter/BasicLogFilter.java
  src/main/java/com/hack/stock2u/global/filter/HttpFilter.java
  src/main/java/com/hack/stock2u/global/filter/HttpLogger.java
  src/main/java/com/hack/stock2u/global/filter/RoleGuardInterceptor.java
  src/main/java/com/hack/stock2u/product/api/ProductApi.java
  src/main/java/com/hack/stock2u/utils/RoleGuard.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: feat

#32 feat: 재고 게시글 조회/수정/삭제 API
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/product/api/ProductApi.java
  src/main/java/com/hack/stock2u/product/dto/ProductDetails.java
  src/main/java/com/hack/stock2u/product/dto/ProductImageSet.java
  src/main/java/com/hack/stock2u/product/service/ProductService.java
  src/main/java/com/hack/stock2u/user/dto/SellerDetails.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
Labels: feat

#34 Feature/su 89
  src/main/java/com/hack/stock2u/chat/controller/ChatRoomController.java
  src/main/java/com/hack/stock2u/chat/controller/ReservationController.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationRequestDto.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationRoomsRequest.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatRoomResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ReservationResponse.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/models/Reservation.java
Labels: feat

#35 feat: 사업자 정보 수정 API / 판매자 회원가입 오류 수정 / 인증 로직 개선
  src/main/java/com/hack/stock2u/authentication/api/AuthApi.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/AuthCodeProvider.java
  src/main/java/com/hack/stock2u/authentication/service/SessionManager.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/models/SellerDetails.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/product/service/ProductService.java
  src/main/java/com/hack/stock2u/user/api/MyApi.java
  src/main/java/com/hack/stock2u/user/api/PurchaserApi.java
  src/main/java/com/hack/stock2u/user/api/SellerApi.java
  src/main/java/com/hack/stock2u/user/repository/JpaSellerRepository.java
  src/main/java/com/hack/stock2u/user/service/MyService.java
  src/main/java/com/hack/stock2u/user/service/PurchaserService.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
  src/main/java/com/hack/stock2u/user/validator/BankName.java
  src/main/java/com/hack/stock2u/user/validator/BankNameValidator.java
Labels: feat, fix

#36 feat: 판매자 구독 API / 판매자 구독 취소 API / 구독한 판매자 정보 리스트 API (pageable)
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/models/Subscription.java
  src/main/java/com/hack/stock2u/product/dto/SimpleProduct.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/product/service/ProductService.java
  src/main/java/com/hack/stock2u/user/api/PurchaserApi.java
  src/main/java/com/hack/stock2u/user/dto/SellerSubscribeDetails.java
  src/main/java/com/hack/stock2u/user/repository/JpaSubscriptionRepository.java
  src/main/java/com/hack/stock2u/user/service/PurchaserService.java
  src/main/java/com/hack/stock2u/user/service/SubscriptionService.java
Labels: feat

#37 feat: HTTP 로깅 개선 / OpenAPI Docs 개선 / 회원가입 이슈 수정
  src/main/java/com/hack/stock2u/authentication/AuthException.java
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/authentication/service/SignupValidator.java
  src/main/java/com/hack/stock2u/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hack/stock2u/global/filter/HttpLogger.java
  src/main/java/com/hack/stock2u/global/filter/MultiReadableRequestBodyHttpServletRequest.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/user/api/MyApi.java
  src/main/java/com/hack/stock2u/user/api/PurchaserApi.java
  src/main/java/com/hack/stock2u/user/dto/SellerDetails.java
  src/main/resources/logback-spring.xml
Labels: feat

#38 fix: verification 값을 vendor 의 유저 식별값으로 변경
  src/main/java/com/hack/stock2u/authentication/dto/SignInResponse.java
  src/main/java/com/hack/stock2u/authentication/service/AuthCodeProvider.java
  src/main/java/com/hack/stock2u/authentication/service/AuthService.java
  src/main/java/com/hack/stock2u/models/User.java
  src/main/java/com/hack/stock2u/user/repository/JpaUserRepository.java
Labels: fix

#39 feat: 위/경도 설계 변경을 API 코드에 반영함
  src/main/java/com/hack/stock2u/authentication/dto/AuthRequestDto.java
  src/main/java/com/hack/stock2u/models/Product.java
  src/main/java/com/hack/stock2u/models/SellerDetails.java
  src/main/java/com/hack/stock2u/product/dto/ProductDetails.java
  src/main/java/com/hack/stock2u/product/dto/ProductRequest.java
  src/main/java/com/hack/stock2u/user/api/SellerApi.java
  src/main/java/com/hack/stock2u/user/dto/SellerRequest.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
Labels: feat

#40 feat: 판매자/구매자 내 정보 조회 API
  build.gradle
  src/main/java/com/hack/stock2u/product/dto/ProductSummary.java
  src/main/java/com/hack/stock2u/product/dto/ProductSummaryProjection.java
  src/main/java/com/hack/stock2u/user/api/PurchaserApi.java
  src/main/java/com/hack/stock2u/user/api/SellerApi.java
  src/main/java/com/hack/stock2u/user/dto/AvatarId.java
  src/main/java/com/hack/stock2u/user/dto/PurchaserSummary.java
  src/main/java/com/hack/stock2u/user/dto/SellerSummary.java
  src/main/java/com/hack/stock2u/user/dto/UserId.java
  src/main/java/com/hack/stock2u/user/repository/PurchaserDslRepository.java
  src/main/java/com/hack/stock2u/user/repository/SellerDslRepository.java
  src/main/java/com/hack/stock2u/user/repository/UserDslRepository.java
  src/main/java/com/hack/stock2u/user/service/PurchaserService.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
Labels: feat

#41 Feature/su 90
  build.gradle
  src/main/java/com/hack/stock2u/chat/config/StompWebSocketConfig.java
  src/main/java/com/hack/stock2u/chat/controller/MessageController.java
  src/main/java/com/hack/stock2u/chat/controller/ReservationController.java
  src/main/java/com/hack/stock2u/chat/controller/StompMessageController.java
  src/main/java/com/hack/stock2u/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationApproveRequest.java
  src/main/java/com/hack/stock2u/chat/dto/request/ReservationRequestDto.java
  src/main/java/com/hack/stock2u/chat/dto/request/SendChatMessage.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ReservationMessageResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/ReservationResponse.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/repository/MessageChatMongoRepository.java
  src/main/java/com/hack/stock2u/chat/service/ChatMessageService.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/chat/web/StompWepSocketConfig.java
  src/main/java/com/hack/stock2u/global/config/RedisConfig.java
  src/main/java/com/hack/stock2u/global/config/SecurityConfig.java
  src/main/java/com/hack/stock2u/models/ChatMessage.java
  src/main/java/com/hack/stock2u/models/Reservation.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
Labels: feat

#44 feat: 일반 사용자 채팅 내역 리스트
  src/main/java/com/hack/stock2u/chat/api/MessageController.java
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/PurchaserReservationsResponse.java
  src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
  src/main/java/com/hack/stock2u/chat/dto/response/SimpleThumbnailImage.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/repository/MessageChatMongoRepository.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/file/repository/JpaAttachRepository.java
  src/main/java/com/hack/stock2u/models/Reservation.java
Labels: feat

#45 feat: 구매자 판매자 공통 채팅 조회 로직 구현
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/dto/response/PurchaserSellerReservationsResponse.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
Labels: feat, fix

#46 feat: 검색으로 채팅방 조회
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
  src/main/java/com/hack/stock2u/models/Reservation.java
Labels: feat, fix

#47 fix: jpareservation에 오류 수정
  src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
  src/main/java/com/hack/stock2u/chat/repository/JpaReservationRepository.java
  src/main/java/com/hack/stock2u/chat/service/ReservationService.java
Labels: bug, fix

#48 feat: 재고 관련 이슈 해결 / 재고 조회 API 요구사항 추가
  build.gradle
  src/main/java/com/hack/stock2u/models/Subscription.java
  src/main/java/com/hack/stock2u/product/dto/ProductCountProjection.java
  src/main/java/com/hack/stock2u/product/dto/ProductDetails.java
  src/main/java/com/hack/stock2u/product/repository/JpaProductRepository.java
  src/main/java/com/hack/stock2u/product/service/ProductService.java
  src/main/java/com/hack/stock2u/user/dto/SellerDetails.java
  src/main/java/com/hack/stock2u/user/repository/JpaSubscriptionRepository.java
  src/main/java/com/hack/stock2u/user/service/SellerService.java
  src/main/resources/application.yaml
Labels: feat, fix
